// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SLACalculator.Infrastructure.Data;

#nullable disable

namespace SLACalculator.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SLACalculator.Domain.Entities.BusinessClosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsFullDayClosure")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("BusinessClosures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosureDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(6719),
                            Description = "Saudi Founding Day",
                            IsFullDayClosure = true,
                            Name = "Saudi Founding Day 2026"
                        },
                        new
                        {
                            Id = 2,
                            ClosureDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(7547),
                            Description = "Saudi Nationl Day",
                            IsFullDayClosure = true,
                            Name = "Saudi Nationl Day 2026"
                        },
                        new
                        {
                            Id = 3,
                            ClosureDate = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Today Event for 4 Hours",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsFullDayClosure = false,
                            Name = "Today event from 6 PM to 10 PM",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("SLACalculator.Domain.Entities.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CaptureDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePaths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlaExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Complaints", (string)null);
                });

            modelBuilder.Entity("SLACalculator.Domain.Entities.SlaConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionTimeInHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SlaConfigurations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(5993),
                            Priority = 1,
                            ResolutionTimeInHours = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(6350),
                            Priority = 2,
                            ResolutionTimeInHours = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(6351),
                            Priority = 3,
                            ResolutionTimeInHours = 24
                        });
                });

            modelBuilder.Entity("SLACalculator.Domain.Entities.WorkingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("WorkingDays", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(820),
                            DayOfWeek = 0,
                            IsWorkingDay = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(1260),
                            DayOfWeek = 1,
                            IsWorkingDay = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(1261),
                            DayOfWeek = 2,
                            IsWorkingDay = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(1262),
                            DayOfWeek = 3,
                            IsWorkingDay = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(1262),
                            DayOfWeek = 4,
                            IsWorkingDay = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(1263),
                            DayOfWeek = 5,
                            IsWorkingDay = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(1264),
                            DayOfWeek = 6,
                            IsWorkingDay = false
                        });
                });

            modelBuilder.Entity("SLACalculator.Domain.Entities.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WorkingHours", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 59, 22, 587, DateTimeKind.Utc).AddTicks(5053),
                            Description = "Everyday Work Hours form 8 AM to 5 PM",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
